### ISSUE TITLE
unable to load hdf5 files

### ISSUE THREAD

**Issue by astromonz** [lspestrip/striptun#12]
When i try to run the following command:

    python output_average.py file.h5

i get the following output:

`````
Traceback (most recent call last):
  File "output_average.py", line 41, in <module>
    main()
  File "output_average.py", line 27, in main
    data = np.loadtxt(args.text_file, skiprows=1)
  File "C:\Users\filip\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 974, in loadtxt
    next(fh)
  File "C:\Users\filip\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2632: character maps to <undefined>
`````

**Comment by ziotom78** [comment]
With the latest commit (d66fee9) it is possible to run tnoise_step1.py and tnoise_step2.py with the URL to the JSON entry of a test. You can test it in the following way:

    python tnoise_step1.py STRIP07 JSON_URL

This is possible thanks to the new module [file_access.py](https://github.com/lspestrip/striptun/blob/master/file_access.py). I'll leave this bug open until the other modules (1/f noise, bandpass, average output) are updated as well.

**Comment by ziotom78** [comment]
Commit 2a167a7f8177b40b3a8d355a3230ce944ce75bdb fixes this issue.
