### ISSUE TITLE
Bandpass analysis fails on some tests

### ISSUE THREAD

**Issue by ziotom78** [lspestrip/striptun#15]
Running `bandwidth.py` on test https://striptest.fisica.unimi.it/unittests/tests/45 fails:
`````
$ python striptun\bandwidth.py -FILE https://striptest.fisica.unimi.it/unittests/tests/45/json STRIP24 STRIP24
[2017-12-06 22:37:19,676 INFO] Tuning radiometer "STRIP24"
[2017-12-06 22:37:19,676 INFO] Writing the report into "STRIP24\bandpass"
[2017-12-06 22:37:19,676 INFO] Loading file "https://striptest.fisica.unimi.it/unittests/tests/45/json"
[2017-12-06 22:37:21,270 INFO] File loaded, 6525 samples found
Traceback (most recent call last):
  File "striptun\bandwidth.py", line 404, in <module>
    main()
  File "striptun\bandwidth.py", line 342, in main
    args.polarimeter_name, file_name, args.output_path)
  File "striptun\bandwidth.py", line 300, in AnalyzeBandTest
    new_nu, new_data)
  File "striptun\bandwidth.py", line 145, in get_central_nu_bandwidth
    raise ValueError('The frequency steps are not uniform! Check out!')
ValueError: The frequency steps are not uniform! Check out!
`````

**Comment by silviacaprioli** [comment]
Hi!
I think it is somehow related to the hdf5 format. I tried to run the code on several tests that I downloaded from the STRIP database but I always get the same error, while on the correspondent .txt files everything works.
The error message comes from the function that calculates central frequency and bandwidth:
    if np.allclose((nu[1:] - nu[:-1]), (nu[1:] - nu[:-1])[0]) is False:
        raise ValueError('The frequency steps are not uniform! Check out!')

And indeed if I print the "array of frequencies" in the two cases  that's what I get:
*hdf5
38.          38.09999847  38.20000076  38.29999924  38.40000153  38.5
  38.59999847  38.70000076  38.79999924  38.90000153  39.          39.09999847
  39.20000076  39.29999924  39.40000153  39.5         39.59999847
  39.70000076  39.79999924  39.90000153  40.          40.09999847
  40.20000076  40.29999924  40.40000153  40.5         40.59999847

*txt
38.   38.1  38.2  38.3  38.4  38.5  38.6  38.7  38.8  38.9  39.   39.1
  39.2  39.3  39.4  39.5  39.6  39.7  39.8  39.9  40.   40.1  40.2  40.3
  40.4  40.5  40.6  40.7  40.8  40.9  41.   41.1  41.2  41.3  41.4  41.5
  41.6  41.7  41.8  41.9  42.   42.1  42.2  42.3  42.4  42.5  42.6  42.7

Any ideas?

**Comment by ziotom78** [comment]
HDF5 files use a binary format, and therefore numbers are saved using base 2. On the other hand, text files use base 10. Since 0.1 can be represented exactly in base 10 but not in base 2, HDF5 rounds the number. As frequencies are saved using 32 bits, this means that you cannot achieve the precision assumed by `np.allclose` (which, in this specific case where Δν=0.1 GHz, is roughly 10 kHz because `rtol=1e-5`).

You can solve the problem by passing a larger value to `rtol` to `np.allclose`, e.g.:

    if !np.allclose((nu[1:] - nu[:-1]), (nu[1:] - nu[:-1])[0], rtol=1e-3):
        # …and so on

(By the way, writing `if !x…` instead of `if x is False` is more Pythonic.)

**Comment by silviacaprioli** [comment]
commit c2d4870a87e01d147af4de0f7776af901afcb0ba fixes this bug
