### ISSUE TITLE
Use calibrated data when computing the spectrum

### ISSUE THREAD

**Issue by ziotom78** [lspestrip/striptun#19]
Now that the striptest site supports retrieving JSON data from noise temperature analyses (see the page «Noise temperature estimates», there is a new column on the right with the link), the `noise_characteristics.py` module should use the best estimates for the four gain factors (G<sub>Q1</sub>, G<sub>U1</sub>, G<sub>U2</sub>, and G<sub>U2</sub>) to properly calibrate the PWR and DEM samples loaded from HDF5 files, and present the results in K<sup>2</sup>/Hz.

**Comment by fincardona** [comment]
Should I use the function `load_timestream` with the syntax `load_timestream('https://striptest.fisica.unimi.it/unittests/api/tnoise/19')` to get the data? 

Because in this case I obtain the following error message: 

```
KeyError                                  Traceback (most recent call last)
<ipython-input-4-eb3aec4c9e4d> in <module>()
----> 1 load_timestream('https://striptest.fisica.unimi.it/unittests/api/tnoise/19?format=json')

/home/federico/Desktop/striptun/file_access.py in load_timestream(file_path)
    162             if content_type == 'application/json':
    163                 metadata = json.loads(req.read().decode('utf-8'))
--> 164                 download_test(file_path, metadata, h5_file)
    165             elif content_type == 'application/hdf5':
    166                 copyfileobj(req, h5_file)

/home/federico/Desktop/striptun/file_access.py in download_test(url, test_info, output_file)
     40     'Copy the HDF5 file related to some test into file object "output_file"'
     41 
---> 42     download_url = urlparse.urljoin(url, test_info['download_url'])
     43     response = urlreq.urlopen(download_url)
     44     copyfileobj(response, output_file)

KeyError: 'download_url'
```

I tried also `load_timestream('https://striptest.fisica.unimi.it/unittests/api/tnoise/19?format=json')` obtaining the same error.

**Comment by ziotom78** [comment]
Use the old `download_test_info` function (in `file_access.py`), which has been renamed into `download_json_from_url` (commit 3f651519101d2329f621d3c9ce4e57dcc836d1ae).

**Comment by fincardona** [comment]
With #21 I convert from ADU to K the data and the spectra.
