### ISSUE TITLE
tuning criteria as input 

### ISSUE THREAD

**Issue by fincardona** [lspestrip/striptun#5]
It would be useful if the operator could set by hand the values of Id (I drain) that the program uses in step 4 (for the HEMT Q1/H0, Q6/H1, Q2/H2, Q5/H3)

**Comment by ziotom78** [comment]
You can now write a JSON file containing the parameters for Id and Vd, using the `-s` command line switch:
`````bash
python striptun.py -s STRIP49_parameters.json STRIP49 ...
`````
where `STRIP49_parameters.json` is a JSON file like this one:
`````json
{
    "ref_vd_mV": 900.0,
    "id_mA_q1_q6": 4.5,
    "id_mA_q2_q5": 7.5,
    "id_mA_q3_q4": 6.5,
    "id_mA_tolerance": 1.5
}
`````

If the `-s` switch is not used, the program will load the settings from [striptun_defaults.json](https://github.com/lspestrip/striptun/blob/master/striptun_defaults.json).
