### ISSUE TITLE
T noise calculation doesn't take into account the case with "load A" varying and "load B" fixed 

### ISSUE THREAD

**Issue by fincardona** [lspestrip/striptun#8]
The values of `self.pwr_constants` in:

https://github.com/lspestrip/striptun/blob/a26d6b81ca46f3e33361a4bef3a58b884b6175bb/tnoise_step2.py#L136-L153

are valid only if one is varying the temperature of "load B" with temperature of "load A" fixed. Otherwise, the blind channel corresponds to the PWR1 detector output.

**Comment by ziotom78** [comment]
Fixed by aa2e348f4febb91b11c61884286f7e9db5bcb2c2
